language: ruby
cache: bundler
rvm:
  - jruby
before_script:
  - bundle exec rake vendor
  - bundle exec rake install_jars
  - ./scripts/travis-before_script.sh
  - source ./scripts/travis-variables.sh
script: bundle exec rspec
